USE [master]
GO

/****** Object:  Database [Dealership]    Script Date: 4/11/2018 3:16:18 PM ******/
CREATE DATABASE [Dealership]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Dealership', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Dealership.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Dealership_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Dealership_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Dealership] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Dealership].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Dealership] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Dealership] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Dealership] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Dealership] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Dealership] SET ARITHABORT OFF 
GO

ALTER DATABASE [Dealership] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Dealership] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Dealership] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Dealership] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Dealership] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Dealership] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Dealership] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Dealership] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Dealership] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Dealership] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Dealership] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Dealership] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Dealership] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Dealership] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Dealership] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Dealership] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Dealership] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Dealership] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Dealership] SET  MULTI_USER 
GO

ALTER DATABASE [Dealership] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Dealership] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Dealership] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Dealership] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Dealership] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Dealership] SET QUERY_STORE = OFF
GO

USE [Dealership]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Dealership] SET  READ_WRITE 
GO


